name: Deploy wp

on:
  release:
    types:
      - published

jobs:
  deploy:
    if: github.event.release.prerelease == false && (github.event.release.target_commitish == 'development' || github.event.release.target_commitish == 'release' || github.event.release.target_commitish == 'main')
    runs-on: ubuntu-20.04
    steps:
      - id: env
        uses: actions/github-script@v3
        with:
          script: |
            return {
              name: context.payload.repository.name,
              version: context.payload.release.tag_name.startsWith('v') ? context.payload.release.tag_name.split('v')[1] : context.payload.release.tag_name
            };
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: |
          echo -e "@noorprojects:registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=$TOKEN\n" > ~/.npmrc
          composer config -g github-oauth.github.com $TOKEN
          npm install
        env:
          TOKEN: ${{secrets.BOT_PAT}}
      - run: |
          npm version ${{fromJson(steps.env.outputs.result).version}} --no-git-tag-version
          npm run production
        env:
          NODE_ENV: production
      - name: Create Release Folder
        run: | 
          rsync -arv . ./${{fromJson(steps.env.outputs.result).name}} --exclude='.*' --exclude='*.git*' --exclude='node_modules' --exclude='composer.*' --exclude='resources' --exclude='package*.json' --exclude='scaffold'
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'release.zip'
          path: ./${{fromJson(steps.env.outputs.result).name}}
          exclusions: 'CHANGELOG.md README.md'

      - name: Create Release Assets
        run: |
          mkdir deploy_dist
          cp release.zip deploy_dist/$REPO_NAME-$VERSION.zip
          cp CHANGELOG.md deploy_dist/CHANGELOG-$VERSION.md
          echo -e "{
            \"version\": \"$VERSION\",
            \"details_url\": \"https://wp-registry.noor-dev.se/registry/themes/$REPO_NAME/CHANGELOG-$VERSION.md\",
            \"download_url\": \"https://wp-registry.noor-dev.se/registry/themes/$REPO_NAME/$REPO_NAME-$VERSION.zip\"
          }" > deploy_dist/metadata.json
        env:
          REPO_NAME: ${{fromJson(steps.env.outputs.result).name}}
          VERSION: ${{fromJson(steps.env.outputs.result).version}}

      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.WP_REGISTRY_HOST}}
          user: ${{ secrets.WP_REGISTRY_FTP_USER }}
          password: ${{ secrets.WP_REGISTRY_FTP_PASSWORD }}
          localDir: "deploy_dist"
          remoteDir: "${{fromJson(steps.env.outputs.result).name}}"

      - uses: softprops/action-gh-release@v1
        with:
          files: deploy_dist/*.zip
